// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmfcuedutkwedrfuvbej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtZmN1ZWR1dGt3ZWRyZnV2YmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2NzgwODcsImV4cCI6MjA4MDI1NDA4N30.wdYvhesxQYX9rKospGovbkOI8Rj6E7GXCtElzmr5f-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});